export const environment = {
  production: true  ,
  //API_HOST: 'http://localhost:17586/',
  //API_HOST: 'http://www.iscar.com/ITA_API/',
  internal: true ,
  API_HOST: 'http://intranet.imc.co.il//ITA_API/',
  IscarLogo: 'https://www.iscar.com/eCatalog/media/images/ISCAR_Logo.svg',
  ImagePath:"assets/img/",
  ImageInputPath:"assets/img/input_images/",
  ImageApplicationsPath:"assets/img/Applications/",
  ImgAddToFavorite:"assets/img/AddToFavoritIcon.svg" ,
  ImgDefault:"assets/img/SetDiffult_Icon.svg" ,
  ImgView:"assets/img/View_Icon.svg",
  ImgSetDefault:"assets/img/SetDiffult_Icon.svg",
  ImgViewTable:"assets/img/AlternativeIcon.svg",
  ImgEditParams:"assets/img/icon_edit_ITA.svg",
  ImgStock:"assets/img/icon_stock.svg",
  ImgArrowLeft:"assets/img/arrows_left.png",
  ImgArrowRight:"assets/img/arrows_right.png",
  ECatalogLink:"http://intranet.imc.co.il/ecatalog/Index.aspx",
  IscarSite:"http://intranet.imc.co.il",
  MachiningCalculatorSite:"https://mpwr.iscar.com/MachiningPower"
};
