export const environment = {
  production: true  ,
  //API_HOST: 'http://localhost:17586/',
  API_HOST: 'http://www.iscar.com/ITA_API/',
  internal: true ,
  //API_HOST: 'http://intranet.imc.co.il//ITA_API/',
  IscarLogo: 'https://www.iscar.com/eCatalog/media/images/ISCAR_Logo.svg',
  ImagePath:"assets/img/",
  ImageInputPath:"assets/img/input_images/",
  ImageApplicationsPath:"assets/img/Applications/",
  ImgAddToFavorite:"assets/img/AddToFavoritIcon.svg" ,
  ImgFavorite:"assets/img/icon_Favorite.svg" ,
  ImgDefault:"assets/img/SetDiffult_Icon.svg" ,
  ImgView:"assets/img/View_Icon.svg",
  ImgSetDefault:"assets/img/SetDiffult_Icon.svg",
  ImgViewTable:"assets/img/AlternativeIcon.svg",
  ImgEditParams:"assets/img/icon_edit_ITA.svg",
  ImgStock:"assets/img/icon_stock.svg",
  ImgArrowLeft:"assets/img/arrows_left.png",
  ImgArrowRight:"assets/img/arrows_right.png",
  ImgThreeDots:"assets/img/threeDots.jpg",
  ImgAssembly:"assets/img/icon_Assembly.svg",
  ECatalogLink:"https://www.iscar.com/eCatalog/Index.aspx",
  IscarSite:"https://www.iscar.com",
  MachiningCalculatorSite:"https://www.iscar.com/mpwrapi/",
  eCatItemPictures:"https://www.iscar.com/ISCARCatalogConfirmPictures/",
  eCatFamilyPictures:"https://www.iscar.com/eCatalog/Ecat/datafile/PICTURE/",
  //eCatFamilyPictures:"https://www.iscar.com/Ecat/datafile/PICTURE/",
  eCatFamilyDrawing:"https://www.iscar.com/eCatalog/Ecat/illust_ISO",
  eCatLogo: "https://www.iscar.com/eCatalog/Ecat/datafile/Logo/",
  
  CalcReq_Host: 'https://mpwr.iscar.com//MachiningPwrWs/api/CalcReq/',
  eCatItemPage:"https://www.iscar.com/ecatalog/item.aspx?type=1&cat=",
  wsMaterials: "http://www.iscar.com/wsmaterials/service.asmx/"
};
